services:
  drupal:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: drupal_app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DRUPAL_DB_HOST: db
      DRUPAL_DB_NAME: ${DB_NAME}
      DRUPAL_DB_USER: ${DB_USER}
      DRUPAL_DB_PASSWORD: ${DB_PASSWORD}
      DRUPAL_DB_PORT: ${DB_PORT:-3306}
      DRUPAL_SITE_NAME: '${DRUPAL_SITE_NAME:-Drupal}'
      ADMIN_USER: ${DRUPAL_ADMIN_USER:-admin}
      ADMIN_PASS: ${DRUPAL_ADMIN_PASS:-admin}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - drupal_data:/var/www/html

  db:
    image: mariadb:10.11
    container_name: drupal_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p\"$DB_ROOT_PASSWORD\" >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:stable-alpine
    container_name: drupal_nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-8080}:80"
    depends_on:
      - drupal
    volumes:
      - drupal_data:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db_data:
  drupal_data:

networks:
  default:
    driver: bridge
