name: assessor-website-2026

services:

  drupal:
    image: drupal:11.1.8-php8.3-fpm
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Configure PHP to show errors in dev (optional)
      PHP_ERRORS: "1"
    volumes:
      - ./web:/var/www/html/web
      - ./vendor:/var/www/html/vendor
      - files-data:/var/www/html/web/sites/default/files
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    image: nginx:1.27-alpine
    depends_on:
      drupal:
        condition: service_started
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html/web:ro
      - ./vendor:/var/www/html/vendor:ro
      - files-data:/var/www/html/web/sites/default/files:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

  db:
    image: mariadb:10.11
    environment:
      MARIADB_DATABASE: drupal
      MARIADB_USER: drupal
      MARIADB_PASSWORD: drupal
      MARIADB_ROOT_PASSWORD: rootpassword
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  # Lightweight DB access tool
  adminer:
    image: adminer:4
    depends_on:
      db:
        condition: service_healthy
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8081:8080"
    restart: unless-stopped

  # Test/inspect outbound emails at http://localhost:8025
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    restart: unless-stopped

volumes:
  db-data:
  files-data:
