services:
  drupal:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: drupal_app
    restart: unless-stopped
    environment:
      DRUPAL_DB_HOST: db
      DRUPAL_DB_NAME: ${DB_NAME}
      DRUPAL_DB_USER: ${DB_USER}
      DRUPAL_DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    volumes:
      - drupal_data:/var/www/html
      - ./web/composer.json:/var/www/html/composer.json
      - ./web/composer.lock:/var/www/html/composer.lock

  db:
    image: mariadb:10.11
    container_name: drupal_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:stable-alpine
    container_name: drupal_nginx
    restart: unless-stopped
    ports:
      - "${PORT_HTTP:-8080}:80"
    depends_on:
      - drupal
    volumes:
      - drupal_data:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db_data:
  drupal_data:

networks:
  default:
    driver: bridge
