version: "3.9"

services:
  db:
    image: mariadb:10.6
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-drupal}
      MYSQL_USER: ${MYSQL_USER:-drupal}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-drupal}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build:
      context: .
      dockerfile: .docker/web/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/web
    volumes:
      - ./:/var/www/html
    env_file:
      - .env

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"

volumes:
  db-data:
